name: Test Echo Action

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "¡Hola, esta es una prueba de GitHub Actions!"
