name: Test Echo Action
on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        run: echo "HUBB_USER=${{ vars.HUBB_USER }}"
