name: Test Echo Action

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  echo-job:
    runs-on: ubuntu-latest
    environment:
      name: devops # Asocia el entorno 'devops'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print environment variable
        run: echo "HUBB_USER=${{ secrets.HUBB_USER }}"
