name: devops-main
on:
  push:
    branches:
      - develop
  workflow_dispatch:

# jobs:
#   echo-job:
#     runs-on: ubuntu-latest
#     environment:
#       name: devops
#     steps:
#       - name: Print environment variable
#         run: echo "HUBB_USER=${{ vars.HUBB_USER }}"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: devops
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ls -la

      # - name: Login to Docker hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
