name: cicd-wander
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image" # Descripción del input
        required: true # Hace que este campo sea obligatorio
        default: "latest"

# jobs:
#   echo-job:
#     runs-on: ubuntu-latest
#     environment:
#       name: devops
#     steps:
#       - name: Print environment variable
#         run: echo "HUBB_USER=${{ vars.HUBB_USER }}"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: devops
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ls -la
      - run: docker --version

      - name: Build docker image
        run: docker build -t ${{ vars.HUBB_USER }}/pruebas-wander:${{ inputs.tag }} . #${{ github.event.inputs.tag }}

      - name: ls images docker
        run: docker images
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.HUBB_USER }}
          password: ${{ secrets.HUBBB }}

      - name: Push to Docker Hub
        run: docker push ${{ vars.HUBB_USER }}/pruebas-wander:${{ inputs.tag }}

      # - run: docker login
#  jose0078/pruebas-wander:node03.1

