name: cicd-wander
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image" # Descripción del input
        required: true # Hace que este campo sea obligatorio
        default: "latest"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: devops
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t ${{ vars.HUBB_USER }}/pruebas-wander:${{ inputs.tag }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.HUBB_USER }}
          password: ${{ secrets.HUBBB }}

      - name: Push to Docker Hub
        run: docker push ${{ vars.HUBB_USER }}/pruebas-wander:${{ inputs.tag }}
